n(NOM, MOT, GENRE, V, V) :- n(NOM, MOT, GENRE).
n(NOM, MOT, nms) :- nm(NOM, [MOT, _]).
n(NOM, MOT, nmp) :- nm(NOM, [_, MOT]).
n(NOM, MOT, nfs) :- nf(NOM, [MOT, _]).
n(NOM, MOT, nfp) :- nf(NOM, [_, MOT]).

% default to tag
n2(SUJET, SUJET, GENRE) :- 
  attr_v(CLASS, SUJET),
  is_word_type(nom_commun, SUJET),
  domain(CLASS, LIST_NOM),
  nth0(INDEX, LIST_NOM, SUJET),
  gender(CLASS, LIST_GENRE), 
  nth0(INDEX, LIST_GENRE, GENRE).
 
nf(poule, [poule, poules]).
nf(aide,[aide,aides]).
nm(chef,[chef,chefs]).
nm(enfant,[enfant,enfants]).
nf(garde,[garde,gardes]).
nf(gauche,[gauche,gauches]).
nm(geste,[geste,gestes]).
nm(gosse,[gosse,gosses]).
nm(livre,[livre,livres]).
nm(merci,[merci,mercis]).
nf(mort,[mort,morts]).
nm(mort,[mort,morts]).
nf(ombre,[ombre,ombres]).
nf(part,[part,parts]).
nf(poche,[poche,poches]).
nf(moto,[moto,motos]).
mn(velo,[vélo,vélos]).
nm(professeur,[professeur,professeurs]).
nf(professeur,[professeur,professeurs]).
nm(tour,[tour,tours]).
nf(tour,[tour, tours]).
nf(fois,[fois,foiss]).
nf(madame,[madame,madames]).
nf(paix,[paix,paix]).
nf(voix,[voix,voix]).
nf(affaire,[affaire,affaires]).
nf(année,[année,années]).
nf(arme,[arme,armes]).
nf(armée,[armée,armées]).
nf(attention,[attention,attentions]).
nf(balle,[balle,balles]).
nf(boîte,[boîte,boîtes]).
nf(bouche,[bouche,bouches]).
nf(carte,[carte,cartes]).
nf(cause,[cause,causes]).
nf(chambre,[chambre,chambres]).
nf(chance,[chance,chances]).
nf(chose,[chose,choses]).
nf(classe,[classe,classes]).
nf(confiance,[confiance,confiances]).
nf(couleur,[couleur,couleurs]).
nf(cour,[cour,cours]).
nf(cuisine,[cuisine,cuisines]).
nf(dame,[dame,dames]).
nf(dent,[dent,dents]).
nf(droite,[droite,droites]).
nf(école,[école,écoles]).
nf(église,[église,églises]).
nf(envie,[envie,envies]).
nf(épaule,[épaule,épaules]).
nf(époque,[époque,époques]).
nf(équipe,[équipe,équipes]).
nf(erreur,[erreur,erreurs]).
nf(espèce,[espèce,espèces]).
nf(face,[face,faces]).
nf(façon,[façon,façons]).
nf(faim,[faim,faims]).
nf(famille,[famille,familles]).
nf(faute,[faute,fautes]).
nf(femme,[femme,femmes]).
nf(fenêtre,[fenêtre,fenêtres]).
nf(fête,[fête,fêtes]).
nf(fille,[fille,filles]).
nf(fleur,[fleur,fleurs]).
nf(force,[force,forces]).
nf(forme,[forme,formes]).
nf(guerre,[guerre,guerres]).
nf(gueule,[gueule,gueules]).
nf(habitude,[habitude,habitudes]).
nf(heure,[heure,heures]).
nf(histoire,[histoire,histoires]).
nf(idée,[idée,idées]).
nf(image,[image,images]).
nf(impression,[impression,impressions]).
nf(jambe,[jambe,jambes]).
nf(joie,[joie,joies]).
nf(journée,[journée,journées]).
nf(langue,[langue,langues]).
nf(lettre,[lettre,lettres]).
nf(lèvre,[lèvre,lèvres]).
nf(ligne,[ligne,lignes]).
nf(lumière,[lumière,lumières]).
nf(main,[main,mains]).
nf(maison,[maison,maisons]).
nf(maman,[maman,mamans]).
nf(manière,[manière,manières]).
nf(marche,[marche,marches]).
nf(merde,[merde,merdes]).
nf(mère,[mère,mères]).
nf(minute,[minute,minutes]).
nf(musique,[musique,musiques]).
nf(nuit,[nuit,nuits]).
nf(odeur,[odeur,odeurs]).
nf(oreille,[oreille,oreilles]).
nf(parole,[parole,paroles]).
nf(partie,[partie,parties]).
nf(peau,[peau,peaus]).
nf(peine,[peine,peines]).
nf(pensée,[pensée,pensées]).
nf(personne,[personne,personnes]).
nf(peur,[peur,peurs]).
nf(photo,[photo,photos]).
nf(pièce,[pièce,pièces]).
nf(pierre,[pierre,pierres]).
nf(place,[place,places]).
nf(police,[police,polices]).
nf(porte,[porte,portes]).
nf(présence,[présence,présences]).
nf(prison,[prison,prisons]).
nf(putain,[putain,putains]).
nf(question,[question,questions]).
nf(raison,[raison,raisons]).
nf(réponse,[réponse,réponses]).
nf(robe,[robe,robes]).
nf(route,[route,routes]).
nf(salle,[salle,salles]).
nf(scène,[scène,scènes]).
nf(seconde,[seconde,secondes]).
nf(sécurité,[sécurité,sécurités]).
nf(semaine,[semaine,semaines]).
nf(situation,[situation,situations]).
nf(soeur,[soeur,soeurs]).
nf(soirée,[soirée,soirées]).
nf(sorte,[sorte,sortes]).
nf(suite,[suite,suites]).
nf(table,[table,tables]).
nf(terre,[terre,terres]).
nf(tête,[tête,têtes]).
nf(vérité,[vérité,vérités]).
nf(ville,[ville,villes]).
nf(voiture,[voiture,voitures]).
nm(avis,[avis,avis]).
nm(bois,[bois,bois]).
nm(bras,[bras,bras]).
nm(choix,[choix,choix]).
nm(corps,[corps,corps]).
nm(cours,[cours,cours]).
nm(gars,[gars,gars]).
nm(mois,[mois,mois]).
nm(pays,[pays,pays]).
nm(prix,[prix,prix]).
nm(propos,[propos,propos]).
nm(sens,[sens,sens]).
nm(temps,[temps,temps]).
nm(travers,[travers,travers]).
nm(vieux,[vieux,vieux]).
nm(accord,[accord,accords]).
nm(agent,[agent,agents]).
nm(amour,[amour,amours]).
nm(appel,[appel,appels]).
nm(arbre,[arbre,arbres]).
nm(argent,[argent,argents]).
nm(avenir,[avenir,avenirs]).
nm(avion,[avion,avions]).
nm(bateau,[bateau,bateaus]).
nm(bébé,[bébé,bébés]).
nm(besoin,[besoin,besoins]).
nm(bonheur,[bonheur,bonheurs]).
nm(bonjour,[bonjour,bonjours]).
nm(bord,[bord,bords]).
nm(boulot,[boulot,boulots]).
nm(bout,[bout,bouts]).
nm(bruit,[bruit,bruits]).
nm(bureau,[bureau,bureaus]).
nf(branche,[branche,branches]).
nm(café,[café,cafés]).
nm(camp,[camp,camps]).
nm(capitaine,[capitaine,capitaines]).
nm(chat,[chat,chats]).
nm(chemin,[chemin,chemins]).
nm(chéri,[chéri,chéris]).
nm(cheval,[cheval,chevals]).
nm(cheveu,[cheveu,cheveus]).
nm(chien,[chien,chiens]).
nf(chien,[chienne,chiennes]).
nm(ciel,[ciel,ciels]).
nm(client,[client,clients]).
nm(cœur,[cœur,cœurs]).
nm(coin,[coin,coins]).
nm(colonel,[colonel,colonels]).
nm(compte,[compte,comptes]).
nm(copain,[copain,copains]).
nm(côté,[côté,côtés]).
nm(coup,[coup,coups]).
nm(courant,[courant,courants]).
nm(début,[début,débuts]).
nm(départ,[départ,départs]).
nm(dieu,[dieu,dieus]).
nm(docteur,[docteur,docteurs]).
nm(doigt,[doigt,doigts]).
nm(dollar,[dollar,dollars]).
nm(doute,[doute,doutes]).
nm(droit,[droit,droits]).
nm(effet,[effet,effets]).
nm(endroit,[endroit,endroits]).
nm(ennemi,[ennemi,ennemis]).
nm(escalier,[escalier,escaliers]).
nm(esprit,[esprit,esprits]).
nm(état,[état,états]).
nm(être,[être,êtres]).
nm(exemple,[exemple,exemples]).
nm(fait,[fait,faits]).
nm(film,[film,films]).
nm(flic,[flic,flics]).
nm(fond,[fond,fonds]).
nm(français,[français,françaiss]).
nm(frère,[frère,frères]).
nm(front,[front,fronts]).
nm(garçon,[garçon,garçons]).
nm(général,[général,générals]).
nm(genre,[genre,genres]).
nm(goût,[goût,goûts]).
nm(gouvernement,[gouvernement,gouvernements]).
nm(grand,[grand,grands]).
nm(groupe,[groupe,groupes]).
nm(haut,[haut,hauts]).
nm(homme,[homme,hommes]).
nm(honneur,[honneur,honneurs]).
nm(hôtel,[hôtel,hôtels]).
nm(instant,[instant,instants]).
nm(intérêt,[intérêt,intérêts]).
nm(intérieur,[intérieur,intérieurs]).
nm(jardin,[jardin,jardins]).
nm(jour,[jour,jours]).
nm(journal,[journal,journals]).
nm(lieu,[lieu,lieus]).
nm(long,[long,longs]).
nm(maître,[maître,maîtres]).
nm(mari,[mari,maris]).
nm(mariage,[mariage,mariages]).
nm(matin,[matin,matins]).
nm(médecin,[médecin,médecins]).
nm(mètre,[mètre,mètres]).
nm(milieu,[milieu,milieus]).
nm(million,[million,millions]).
nm(moment,[moment,moments]).
nm(monde,[monde,mondes]).
nm(monsieur,[monsieur,monsieurs]).
nm(mouvement,[mouvement,mouvements]).
nm(moyen,[moyen,moyens]).
nm(noir,[noir,noirs]).
nm(nouveau,[nouveau,nouveaus]).
nm(numéro,[numéro,numéros]).
nm(oiseau,[oiseau,oiseaux]).
nm(oncle,[oncle,oncles]).
nm(ordre,[ordre,ordres]).
nm(papa,[papa,papas]).
nm(papier,[papier,papiers]).
nm(parent,[parent,parents]).
nm(passage,[passage,passages]).
nm(passé,[passé,passés]).
nm(patron,[patron,patrons]).
nm(père,[père,pères]).
nm(petit,[petit,petits]).
nf(taille,[taille,tailles]).
nm(peuple,[peuple,peuples]).
nm(pied,[pied,pieds]).
nm(plaisir,[plaisir,plaisirs]).
nm(plan,[plan,plans]).
nf(patte,[patte, pattes]).
nf(aile,[aile, ailes]).
nm(point,[point,points]).
nm(pouvoir,[pouvoir,pouvoirs]).
nm(premier,[premier,premiers]).
nm(présent,[présent,présents]).
nm(président,[président,présidents]).
nm(prince,[prince,princes]).
nm(problème,[problème,problèmes]).
nm(quartier,[quartier,quartiers]).
nm(rapport,[rapport,rapports]).
nm(regard,[regard,regards]).
nm(reste,[reste,restes]).
nm(retard,[retard,retards]).
nm(retour,[retour,retours]).
nm(rêve,[rêve,rêves]).
nm(revoir,[revoir,revoirs]).
nm(salut,[salut,saluts]).
nm(sang,[sang,sangs]).
nm(secret,[secret,secrets]).
nm(seigneur,[seigneur,seigneurs]).
nm(sentiment,[sentiment,sentiments]).
nm(service,[service,services]).
nm(seul,[seul,seuls]).
nm(siècle,[siècle,siècles]).
nm(signe,[signe,signes]).
nm(silence,[silence,silences]).
nm(soir,[soir,soirs]).
nm(soldat,[soldat,soldats]).
nm(soleil,[soleil,soleils]).
nm(sourire,[sourire,sourires]).
nm(souvenir,[souvenir,souvenirs]).
nm(sujet,[sujet,sujets]).
nm(téléphone,[téléphone,téléphones]).
nm(tout,[tout,touts]).
nm(train,[train,trains]).
nm(travail,[travail,travails]).
nm(trou,[trou,trous]).
nm(truc,[truc,trucs]).
nm(type,[type,types]).
nm(vent,[vent,vents]).
nm(ventre,[ventre,ventres]).
nm(verre,[verre,verres]).
nm(village,[village,villages]).
nm(visage,[visage,visages]).
nm(voyage,[voyage,voyages]).
nm(fils,[fils,fils]).
nm(gens,[personne, gens]).
nf(gorge,[gorge,gorges]).
nm(menton,[menton,mentons]).
nf(mine,[mine,mines]).
nm(squelette,[squelette,squelettes]).
nm(cil,[cil,cils]).
nm(sourcil,[sourcil,sourcils]).
nm(os,[os,os]).
nm(os,[os,os]).
nf(figure,[figure,figures]).
nf(joue,[joue,joues]).
nm(nez,[nez,nezs]).
nm(oeil,[oeil,yeux]).
nm(doigts,[doigts,doigtss]).
nm(dos,[dos,doss]).
nm(épaule,[épaule,épaules]).
nf(cheville,[cheville,chevilles]).
nf(cuisse,[cuisse,cuisses]).
nm(cou,[cou,cous]).
nm(coude,[coude,coudes]).
nf(fesse,[fesse,fesses]).
nm(genou,[genou,genous]).
nf(hanche,[hanche,hanches]).
nf(jambe, [jambe,jambes]).
nm(muscle,[muscle,muscles]).
nm(ongle,[ongle,ongles]).
nm(pied,[pied,pieds]).
nm(poignet,[poignet,poignets]).
nm(poing,[poing,poings]).
nm(pouce,[pouce,pouces]).
nm(pouce,[pouce,pouces]).
nm(pouce,[pouce,pouces]).
nm(lèvre,[lèvre,lèvres]).
nm(animal,[animal, animaux]).
nf(plante,[plante,plantes]).